    services:
      db:
        image: postgres:latest
        container_name: objetos_laravel
        environment:
          POSTGRES_DB: objetos_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - "5433:5432"
        volumes:
          - postgres_data:/var/lib/postgresql/data

    volumes:
      postgres_data:
